### PR TITLE
auto decaptcha with crawl_course

### PR DESCRIPTION
**Pull request by afq984**
note that the new module `crawler.decaptcha` requires `tesseract` binary and `lxml`

tested locally with PostgreSQL

### CODE REVIEW

**Comment by henryyang42** [comment]
There are some issues after testing on my local.
-  I got `read_params_file: Can't open tessedit_char_whitelist=0123456789` 
- It create a `-.txt` for me instead of output to stdout

It works, however, if I try to change command like `tesseract 2.png  a -psm 8 nobatch digits`
and then read output from `a.txt`

My tesseract version and other dependency:

```
tesseract 3.02.02
 leptonica-1.71
  libjpeg 8d : libpng 1.6.17 : libtiff 4.0.3 : zlib 1.2.5
```

**Comment by afq984** [comment]
my versions

```
$ tesseract --version
tesseract 3.03
 leptonica-1.71
  libgif 5.1.0 : libjpeg 8d : libpng 1.6.16 : libtiff 4.0.3 : zlib 1.2.8 : libwebp 0.4.3
```

will look into it later, thanks

**Comment by afq984** [comment]
a quick note here:
I used `tessedit_char_whitelist=0123456789` instead of `digits` 
because the `digits` file in my distribution contains `-` and `.`

```
$ cat /usr/share/tessdata/configs/digits 
tessedit_char_whitelist 0123456789-.
```

**Comment by henryyang42** [comment]
Yes, it's just a dependency issue.
It works wonderfully if I change my tesseract version to 3.03

**Comment by henryyang42** [comment]
Could you push this PR to branch `dev` so that I can merge it for further testing?

**Comment by afq984** [comment]
pushed to
https://github.com/afg984/NTHU_Course/tree/dev

**Comment by afq984** [comment]
merged-

**Pull request closed without merging**
