### PR TITLE
Course crawler lxml

### PR DESCRIPTION
**Pull request by afq984**
change overview:
1. Course.syllabus no longer contains html, pure text only, _patch needed_ for PDF link
2. extracting info with `lxml` reduces about 1 minute (6 -> 5 min) on my laptop

todo:
1. check crawled stuff is the same

### CODE REVIEW

**Comment by henryyang42** [comment]
Can you try current master `crawl_course` on your laptop?
Current master takes 3 and a half minute on my machine now.

**Comment by afq984** [comment]
current master took 388 secs after `crawl_course clean`

**Comment by henryyang42** [comment]
Nice refactor

**Comment by afq984** [comment]
don't deploy this yet
as
I'm not sure about its correctness and the _觀看上傳之PDF_ will be missing

**Pull request merged**
